#+STARTUP: content

* German Woerterbuch for Emacs                                   :Noexport_2:

[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]] [[https://github.com/hubisan/woerterbuch/actions/workflows/tests.yml][https://github.com/hubisan/woerterbuch/actions/workflows/tests.yml/badge.svg]]

Retrieve definitions (meanings) and synonyms for German words with Emacs.

** TODOS

*** NEXT Add synonyms from Wiktionary

There is already some code in the file that sort of works.
Also make this work if no synonyms where found on Openthesaurus.

*** TODO Add tests to cover more

*** TODO Add customization to include more text from DWDS

Especially the following:

- Beispiele ~<div class="dwdswb-verwendungsbeispiele">~
- Die ganze Definition ~<div class="dwdswb-lesart-def">~ anstelle von nur dem Wort.
  
Either use a defcustom or a function parameter. This doesn't make sense when showing the words in the minibuffer with completion. So only for functions which show the definitions in an org mode buffer.
  
*** TODO Add a way to lookup Redewendungen

- [[https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Sprichw%C3%B6rter][Verzeichnis:Deutsch/Sprichwörter – Wiktionary]]
- [[https://de.wikipedia.org/wiki/Liste_deutscher_Redewendungen][Liste deutscher Redewendungen – Wikipedia]]

** TODO Add image before Main features

** Main features                                                :noexport_0:

    - Retrieve definitions (meanings) or synonyms for a word and
      - display in an Org-mode buffer,
      - insert into the current Org-mode buffer, or
      - add to the kill ring as Org-mode syntax.
    - Retrieve definitions and synonyms simultaneously.
    - Select a synonym for a word and
      - insert it into the current buffer,
      - replace the word at point with it, or
      - add it to the kill ring.

The word used for retrieval can be read from the minibuffer or taken from point.

Definitions are retrieved from [[https://www.dwds.de/]] and synonyms from [[https://www.openthesaurus.de/]]. Optionally synonyms from https://de.wiktionary.org can be retrieved as well.

If anyone knows a better way to get definitions or synonyms than parsing Dwds and Wiktionary, please open an issue. [[https://github.com/hdaSprachtechnologie/odenet][Open German WordNet]] looks promising but needs time to mature.

-----

** Contents

- [[#installation][Installation]]
- [[#usage][Usage]]
- [[#customization][Customization]]
- [[#key-bindings][Key Bindings]]
- [[#changelog][Changelog]]
- [[#contributing][Contributing]]

** Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

# Describe how to install this package.

This package is hosted on Github. Use your favourite way to install like [[https://github.com/progfolio/elpaca][Elpaca]], [[https://github.com/radian-software/straight.el][Straight]], [[https://github.com/quelpa/quelpa][Quelpa]]. Starting with Emacs 29 ~package-vc-install~ may be used.

** Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:

*** Show Definitions

*** Show Synonyms

If a word is not in its baseform, the synonyms for the baseform are looked up (the baseform for Fahrzeuge is Fahrzeug for instance).

- ~woerterbuch-synonyms-show-in-org-buffer~ \\
  Show the synonyms for a word in an Org buffer. Reads the word from the minibuffer.
- ~woerterbuch-synonyms-show-in-org-buffer-for-word-at-point~ \\
  Show the synonyms for a word at point in an Org buffer.
- ~woerterbuch-synonyms-insert-into-org-buffer~ \\
  Read a word from the minibuffer and insert the synonyms as a list into the current Org buffer. If called with a prefix arg (C-u), it adds a heading with the word as the title before the list.
- ~woerterbuch-synonyms-kill-as-org-mode-syntax~ \\
  Add the synonyms for word read from the minibuffer to the kill ring as Org syntax. If called with a prefix arg (C-u), it adds a heading with the word as title before the list.
- ~woerterbuch-synonyms-insert~ \\
  Lookup synonyms for word read from minibuffer and insert selected word at point. If called with a prefix arg (C-u) the selected word is added to the kill ring instead.
- ~woerterbuch-synonyms-lookup-word-at-point~ \\
  Lookup synonyms for word at point and add to kill ring. 
- ~woerterbuch-synonyms-replace-word-at-point~ \\
  Lookup synonyms for wort at point or selection and replace it. 
  
*** Show Definitions and Synonyms

*** Select a Synonym 

** Customization
:PROPERTIES:
:CUSTOM_ID: customization
:END:

*** Variables

Set the following variables to change the behaviour of the package:

- ~woerterbuch-org-buffer-display-function~  #'pop-to-buffer \\
  Function used to the display the org buffer with the definitions or synonyms. The function takes buffer as argument. There is also a function provided to show it in a side window: 
  #+BEGIN_SRC emacs-lisp
    ;; Set the variable:
    (setq woerterbuch-org-buffer-display-function
          (apply-partially #'woerterbuch--display-in-side-window 'right nil))
    ;; Or use it in a let binding:
    (let* ((woerterbuch-org-buffer-display-function
            (apply-partially #'woerterbuch--display-in-side-window 'right 20)))
      (woerterbuch-synonyms-show-in-org-buffer))
  #+END_SRC
- ~woerterbuch-list-bullet-point~  "-" \\
  String to use as list bullet point when converting synonyms or definitions to a list.
- ~woerterbuch-insert-org-heading-format~  "%s %s\n\n%s" \\
  Format used when inserting an Org heading before content.

*** Faces

The package defines no faces.

** Key Bindings
:PROPERTIES:
:CUSTOM_ID: key-bindings
:END:

- @@html:<kbd>@@C-c C-q@@html:</kbd>@@ is bound to ~quit-window~ in the Org buffer showing the definitions or synonyms.

*** Hydra

# Example of a hydra definition.
# TODO show code to define a hydra.

** Changelog
:PROPERTIES:
:CUSTOM_ID: changelog
:END:

See the [[./CHANGELOG.org][changelog]].

** Contributing
:PROPERTIES:
:CUSTOM_ID: contributing
:END:

Use the issue tracker to reports bugs, suggest improvements or propose new features. If you want to contribute please open a pull request after having opened a new issue.

In any case please check out the [[./CONTRIBUTING.org::*Contributing][contributing guidelines]] beforehand.

** Remarks

*** Synonyms

**** Openthesaurus

The text returned can contains additional information in parentheses.

Examples:

#+BEGIN_EXAMPLE
- aufsetzen (Schreiben, Kaufvertrag, ...)
- errichten (Testament, Patientenverfügung, ...)
- (die) Probe aufs Exempel
#+END_EXAMPLE

This information is removed, when reading from the minibuffer. Else it is not removed and inserted into the buffer.

**** Wiktionary

It appears that when composing synonyms on Wiktionary, users have the a lot of freedom to formulate the text. Therefore, I avoid parsing the synonyms into a list which is used when reading from the minibuffer. Similar to OpenThesaurus, the synonyms are inserted into an Org buffer exactly as they are formulated.

Examples of texts used (word 'geben'):

#+BEGIN_EXAMPLE
- abtreten, reichen, übertragen, vermachen
- aushändigen, hinreichen, in die Hand drücken, übergeben, überlassen, überreichen
  gehoben: darbieten, darreichen, zukommen/zuteilwerden lassen
  oft gehoben: reichen
  bildungssprachlich: präsentieren
  umgangssprachlich: langen, rüberwachsen lassen
  Papierdeutsch: verabreichen; Papierdeutsch veraltend: verabfolgen
- schenken, gewähren, zum Geschenk machen, zustecken
  schweizerisch: vergaben
  gehoben: bedenken, beglücken, stiften, zukommen/zuteilwerden lassen
  umgangssprachlich: spendieren
  gehoben oder ironisch angedeihen lassen
  leicht scherzhaft: verehren
  veraltet: zueignen
#+END_EXAMPLE
