#+TITLE: Wörterbuch - TODOs
#+STARTUP: showall
#+TODO: TODO(t) NEXT(n) WAIT(w) REVIEW(r) | DONE(d) CANCEL(c)

Instruktionen für AI-Agents sind in AGENTS.md.

* DONE Manueller Vergleich

Habe einige Wörter ausgewertet mit der aktuellen Funktion und manuell mit der Webseite abgeglichen.

Bitte Tasks markiert mit NEXT in dem File lösen und in dem File dann auf REVIEW setzen. Bitte prüfe den Output nach Anpassungen und vergleiche ihn mit dem alten Output. Nur die Fehler sollten gelöst werden, der Rest darf sich nicht verändern. Speichere den neuen Output in tmp/woerterbuch-export-JJJJ-MM-TT, speichere auch gleich jeweils das Html in diesem Ordner. Vergleiche doch auch gleich das Html mit dem Output, allenfalls erkennst du ja Unstimmmigkeiten. Falls ja mir mitteilen.

** DONE Neuer Fehler - Redewendungen Wiktionary [2026-05-21 Thu]

Da haben wir etwas verschlimmbessert. Hier bei einer Redewendung mehrere Einträge (ist die gleiche Redewendung, aber anders formuliert):

#+BEGIN_SRC html
  <dd id="mwBXo">[2] <a rel="mw:WikiLink" href="//de.wiktionary.org/wiki/etwas_steht_auf_dem_kurzen_Weg_ins_Haus?action=edit&amp;redlink=1" title="etwas steht auf dem kurzen Weg ins Haus (Seite nicht vorhanden)" class="new" typeof="mw:LocalizedAttrs" id="mwBXs" data-mw-i18n="{&quot;title&quot;:{&quot;lang&quot;:&quot;x-page&quot;,&quot;key&quot;:&quot;red-link-title&quot;,&quot;params&quot;:[&quot;etwas steht auf dem kurzen Weg ins Haus&quot;]}}">etwas steht auf dem kurzen Weg ins <i id="mwBXw">Haus</i></a><sup about="#mwt214" class="mw-ref reference" id="cite_ref-Küpper_9-11" rel="dc:references" typeof="mw:Extension/ref" data-mw="{&quot;name&quot;:&quot;ref&quot;,&quot;attrs&quot;:{&quot;name&quot;:&quot;Küpper&quot;}}"><a href="#cite_note-Küpper-9" id="mwBX0"><span class="mw-reflink-text" id="mwBX4"><span class="cite-bracket" id="mwBX8">[</span>9<span class="cite-bracket" id="mwBYA">]</span></span></a></sup>/<a rel="mw:WikiLink" href="//de.wiktionary.org/wiki/etwas_steht_übern_kurzen_Weg_ins_Haus?action=edit&amp;redlink=1" title="etwas steht übern kurzen Weg ins Haus (Seite nicht vorhanden)" class="new" typeof="mw:LocalizedAttrs" id="mwBYE" data-mw-i18n="{&quot;title&quot;:{&quot;lang&quot;:&quot;x-page&quot;,&quot;key&quot;:&quot;red-link-title&quot;,&quot;params&quot;:[&quot;etwas steht übern kurzen Weg ins Haus&quot;]}}">etwas steht übern kurzen Weg ins <i id="mwBYI">Haus</i></a><sup about="#mwt215" class="mw-ref reference" id="cite_ref-Küpper_9-12" rel="dc:references" typeof="mw:Extension/ref" data-mw="{&quot;name&quot;:&quot;ref&quot;,&quot;attrs&quot;:{&quot;name&quot;:&quot;Küpper&quot;}}"><a href="#cite_note-Küpper-9" id="mwBYM"><span class="mw-reflink-text" id="mwBYQ"><span class="cite-bracket" id="mwBYU">[</span>9<span class="cite-bracket" id="mwBYY">]</span></span></a></sup></dd>
#+END_SRC

Vor der Anpassung war dies so:

#+BEGIN_SRC emacs-lisp
  "etwas steht auf dem kurzen Weg ins Haus / etwas steht übern kurzen Weg ins Haus"
#+END_SRC

Neu ist es so:

#+BEGIN_SRC emacs-lisp
  "etwas steht auf dem kurzen Weg ins Haus"
#+END_SRC

** DONE Vergleich Diff Neu mit Alt

** DONE Tests ausführen

Diese Tests kann ich gleich hier ausführen, für den Vergleich.

Gute Tests:

- Bank - 2 getrennte Bedeutungen (homograph)
- Haus - sehr viele Bedeutungen
- Zaun - viele Redewendungen
- das Gras ist grüner auf der anderen Seite - MWA
- Nixdaexistiert - für 404
- springt - einfach noch, damit mehr Tests
- Wolke - einfach noch, damit mehr Tests
- verliebt - einfach noch, damit mehr Tests

*** Alle ausführen und speichern

#+NAME: fetch-words
- Bank
- Haus
- springt
- verliebt
- Wolke
- Zaun
- das Gras ist grüner auf der anderen Seite
- Nixdaexistiert

#+NAME: fetch-sources
- openthesaurus
- dwds
- duden
- wiktionary

#+BEGIN_SRC emacs-lisp :results value code replace :var dir="./tmp/woerterbuch-export-2026-05-21/" :var split-sections=(eval nil) :var words=fetch-words :var sources=fetch-sources :results silent
  (let ((dir (expand-file-name dir default-directory))
        (sections '(:definitions :examples :origin :synonyms :idioms))
        (woerterbuch-sources sources))
    (make-directory dir t)
    (dolist (word words)
      (let ((result
             (woerterbuch-fetch-all-sync
              word
              :sections sections
              :timeout 10)))
        (if split-sections
            (maphash
             (lambda (section value)
               (with-temp-file
                   (expand-file-name
                    (format "%s-%s.el"
                            word
                            (string-remove-prefix ":" (symbol-name section)))
                    dir)
                 (prin1 value (current-buffer))
                 (terpri)))
             result)
          (with-temp-file (expand-file-name (format "%s.el" word) dir)
            ;; (insert ";;; -*- lexical-binding: t; -*-\n\n")
            ;; (insert "'")
            (pp result (current-buffer))
            (terpri))))))
#+END_SRC

*** Bank

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "Bank"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** Haus

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "Haus"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** Zaun

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "Zaun"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** das Gras ist grüner auf der anderen Seite

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "das Gras ist grüner auf der anderen Seite"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** Nixdaexistiert

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "nixtdaexistiert"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** springt

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "springt"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** Wolke

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "Wolke"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

*** verliebt

Wieso auch immer, das Lemma wird verlieben. Habe es mit verschiedenen Lemmatizer ausprobiert.

#+BEGIN_SRC emacs-lisp :results value code replace
  (woerterbuch-fetch-all-sync
   "verliebt"
   :sections  '(:definitions :examples :origin :synonyms :idioms)
   :timeout 10)
#+END_SRC

* CANCEL Spezifikation aktualisieren oder erstellen

In [[file:docs/]] die Spezifikationen updaten und nicht vorhandene erstellen.

* REVIEW Testing

[2026-05-21 Thu 23:39] Update: Noch Checkdoc Warnungen beheben:

#+BEGIN_SRC text

  >>> checkdoc

  `lisp/woerterbuch.el` with checkdoc (0.6.2)
  No issues found

  `lisp/woerterbuch-core.el` with checkdoc (0.6.2)
  woerterbuch-core.el:0: You should have a section marked ";;; Commentary:"
  woerterbuch-core.el:10: You should have a section marked ";;; Code:"
  woerterbuch-core.el:386: Messages should start with a capital letter

  `lisp/woerterbuch-duden.el` with checkdoc (0.6.2)
  woerterbuch-duden.el:0: You should have a section marked ";;; Commentary:"
  woerterbuch-duden.el:11: You should have a section marked ";;; Code:"
  woerterbuch-duden.el:560: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-duden.el:607: Argument ‘input’ should appear (as INPUT) in the doc string
  woerterbuch-duden.el:678: Argument ‘input’ should appear (as INPUT) in the doc string
  woerterbuch-duden.el:716: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-duden.el:742: Argument ‘sections’ should appear (as SECTIONS) in the doc string

  `lisp/woerterbuch-dwds.el` with checkdoc (0.6.2)
  woerterbuch-dwds.el:0: You should have a section marked ";;; Commentary:"
  woerterbuch-dwds.el:11: You should have a section marked ";;; Code:"
  woerterbuch-dwds.el:453: Argument ‘dom’ should appear (as DOM) in the doc string
  woerterbuch-dwds.el:602: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-dwds.el:652: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-dwds.el:686: Argument ‘sections’ should appear (as SECTIONS) in the doc string

  `lisp/woerterbuch-openthesaurus.el` with checkdoc (0.6.2)
  woerterbuch-openthesaurus.el:0: You should have a section marked ";;; Commentary:"
  woerterbuch-openthesaurus.el:8: You should have a section marked ";;; Code:"
  woerterbuch-openthesaurus.el:28: Argument ‘sections’ should appear (as SECTIONS) in the doc string

  `lisp/woerterbuch-wiktionary.el` with checkdoc (0.6.2)
  woerterbuch-wiktionary.el:0: You should have a section marked ";;; Commentary:"
  woerterbuch-wiktionary.el:11: You should have a section marked ";;; Code:"
  woerterbuch-wiktionary.el:490: Argument ‘lemma’ should appear (as LEMMA) in the doc string
  woerterbuch-wiktionary.el:608: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-wiktionary.el:652: Argument ‘sections’ should appear (as SECTIONS) in the doc string
  woerterbuch-wiktionary.el:684: Argument ‘sections’ should appear (as SECTIONS) in the doc string
#+END_SRC


Es soll nur dies getestet werden, bitte bisherige Testsfiles für die Sources neu aufsetzen. Kann man wohl einfach leeren.

- Die HTML lade ich fix runter und speichere sie.
  Habe eine Funktion in test-woerterbuch.el gemacht, welche mir die html runterlädt und dann den erwarteten Output generiert. Habe es ausgeführt. Ist alles im Testordner im Ordner Files bereit = musst du nicht mehr machen.
- Der erwartete Output ist pro Source und Section einzeln.
- Bei Duden hat es auch das Search HTML für Bank, wo es 2 Homographen hat.
- Jetzt einfach mit Buttercup die Tests schreiben und den Output generieren, dabei die gespeicherten Html/Json als Mockup (oder wie dies heisst) verwenden.
- Natürlich pro Source und Section wie der erwartete Output. Von der Test-Funktion kopieren, wie dieser in die Datei eingefügt wird (mit pp und newline am ende)
- Dann prüfen ob die Objekte jeweils gleich sind. Keine weitere Tests sind notwendig.

Periodisch werde ich dann den erwarteten Output aktualisieren und prüfen, was sich verändert hat. Mache ich manuell. Da ich aber das Package viel brauche, werde ich Fehler sowieso rasch entdecken.

* TODO Output definieren

Am Schluss will ich das Ganze als Org ausgeben.

#+BEGIN_SRC emacs-lisp
  (setq org-list-allow-alphabetical t)
#+END_SRC

#+BEGIN_SRC org
  ,#+TITLE: Haus
  allenfalls weitere Properties wie Time

  ,* Bedeutungen

  ,** *DWDS Bedeutungen*

  1. *aus Wänden und Dach errichtetes Gebäude für Menschen*
     a) *zum Wohnen, Wohnhaus*
     - Beispiele
       - ein großes, mehrstöckiges, neues, stattliches, modernes, ruhiges, wohnliches, hässliches, baufälliges, abgewohntes, leeres, verlassenes, zerbombtes, abgebranntes Haus
       - sein elterliches Haus
     - *das eigene Heim*
       - Beispiele
         - im Haus des Freundes ein- und ausgehen
         - eine Einladung, ein Brief flattert ins Haus
     b) ...

  ,** *Duden Bedeutungen*

  Bedeutungen
  1. *aus Wänden und Dach errichtetes Gebäude für Menschen*
     a) *zum Wohnen, Wohnhaus*

  ,** *Wiktionary Bedeutungen*

  ...

  ,* Synonyme

  ,** *Openthesaurus Synonyme*

  ...

  ,** *Duden Synonyme*

  ...

  ,** *Wiktionary Synonyme*

  ...

  ,* Redewendungen

  ,* Herkunft
#+END_SRC

* Allgemeines

** Ziel

Für mehrere Dictionary-Sources (z. B. Duden, DWDS, OpenThesaurus, Wiktionary) sollen Requests *asynchron gleichzeitig gestartet* werden.

Jede Source implementiert dieselbe öffentliche API und liefert das Resultat in einem gemeinsamen plist-Format zurück.

Die Argumente und internen Bezeichner bleiben auf Englisch, auch wenn das Package sonst deutsch ist.

** Korrigierte Architektur

Der Aggregator sollte direkt in =woerterbuch-core.el= liegen.

Begründung:

- dort liegen bereits die gemeinsamen Datenstrukturen und Hilfsfunktionen
- der Aggregator ist keine UI-Schicht, sondern gemeinsame Infrastruktur
- =woerterbuch.el= kann dadurch bewusst dünn bleiben
- so verhindert man, dass Logik versehentlich zwischen =core= und =woerterbuch.el= auseinanderläuft

*** Dateien

- =woerterbuch-core.el=
- =woerterbuch.el=
- =woerterbuch-duden.el=
- =woerterbuch-dwds.el=
- =woerterbuch-openthesaurus.el=
- =woerterbuch-wiktionary.el=

*** Verantwortlichkeiten

**** =woerterbuch-core.el=
Gemeinsame Infrastruktur:
- section handling
- common result helpers
- error/result constructors
- buffer/header helpers
- gemeinsame Request-Helfer
- *Aggregator für alle Sources*
- ggf. zentrale Source-Reihenfolge oder Source-Registry

**** =woerterbuch-<source>.el=
Jeweils source-spezifisch:
- URL building
- HTTP request via =url-retrieve=
- parsing of HTML or JSON
- extraction of requested sections
- returning a normalized plist result

**** =woerterbuch.el=
Nur öffentliche Hülle:
- =require= von =woerterbuch-core.el=
- =require= der einzelnen Sources
- ggf. sehr kleine öffentliche Einstiegspunkte
- keine eigentliche Aggregator- oder Parsing-Logik
