(:input "Zaun" :lemma "Zaun" :sources
        ((:source dwds :lemma "Zaun" :ok t :url "https://www.dwds.de/wb/Zaun"
                  :homographs
                  ((:id 1 :hidx "" :lemma "Zaun" :title "Zaun, der" :wortart
                        "Substantiv" :grammar
                        "Substantiv (Maskulinum) · Genitiv Singular: Zaun(e)s · Nominativ Plural: Zäune"
                        :origin
                        "Zaun m. ‘Abgrenzung, Einfriedung’, ahd. (8. Jh.), mhd. zūn ‘Umzäunung, Hecke, Gehege’, asächs. mnd. tūn ‘Flechtzaun, Gehege, Garten’, mnl. tuun ‘Flechtzaun, umzäunter Hof’, nl. tuin ‘Garten’, aengl. tūn ‘Zaun, Garten, Feld, Hof, Landhaus, Wohnung, Dorf, Stadt’, engl. town ‘Stadt’, anord. tūn n. ‘eingehegter Grasplatz vor dem Hause, Hofplatz, Stadt’, schwed. (mundartlich) tun ‘Zaun’ (germ. *tūna-). Außergerm. Anknüpfungsmöglichkeiten finden sich im Kelt., vgl. air. dūn, akymr. din ‘Burg’ und gall.-lat. -dūnum in Ortsnamen, vgl. Tarodūnum (Zarten), Lugdūnum (Lyon), Virodūnum (Verdun). Redensartlich etw., einen Streit, Krieg vom Zaun brechen ‘unvermittelt heraufbeschwören’ (15. Jh.). – zäunen Vb. ‘einen Zaun errichten’, ahd. zūnen (11. Jh.; vgl. bizūnen, 8. Jh.), mhd. ziunen ; heute einzäunen Vb. (16. Jh.) oder umzäunen Vb., mhd. umbeziunen. Zaunkönig m. Name des sehr kleinen Singvogels, zuerst md. czune künnyck (15. Jh.). Zuvor bezeichnen schon ahd. kuning (eigentlich ‘König’) sowie die Deminutiva ahd. kuningil, kunningilīn, kunningilo, kuninglihhīn in der Übersetzung von lat. rēgulus, psittacus, mlat. bitriscus, bitrisculus einen ‘kleinen Vogel’, offenbar den ‘Zaunkönig’ bzw. das ‘Goldhähnchen’ (dessen gelbe Kopffedern als Krone gedeutet werden können), und zwar im Hinblick auf die Sage von der Königswahl der Vögel (erwähnt bei Aristoteles und Plinius). Danach sollte dem die Königswürde zuerkannt werden, der am höchsten fliegen könne. Den Wettstreit gewann der kleinste Vogel, der sich im Gefieder des am höchsten fliegenden Adlers verbarg und über diesen emporflatterte, als der Adler nicht mehr höher zu fliegen vermochte."
                        :idioms nil :definitions nil)))))
