name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.org'
    # branches:
    #   - main
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.org'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        emacs-version:
          - snapshot
          # for some reason 29.4 gives an error with elint. base64.el not
          # in path or so. No idea why.
          # - 29.4
          # - snapshot
        experimental: [false]
        # include:
        # - os: ubuntu-latest
        #   emacs-version: snapshot
        #   experimental: true

    steps:
    - uses: actions/checkout@v4

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run tests
      run: |
        make all
        make clean
